# -*- coding: utf-8 -*-
"""
Reproduce Figure 1: SEAS5 post-SSW 2-m temperature anomaly composites.

The script calculates raw and linearly detrended composites of daily
SEAS5 2-m temperature anomalies for days 15-59 after SSW onset, shown
for successive periods.

Input:
    - Daily SEAS5 2-m temperature files.
    - A SEAS5 SSW-event CSV generated by 02_seas5_ssw_dates.py.
    - Optionally, an ERA5 SSW-event CSV generated by
      01_era5_ssw_dates.py.

Output:
    Intermediate NPZ files and the Figure 1 PDF in OUTPUT_DIR.

Raw ERA5 and SEAS5 data are not redistributed with this repository.
Update the paths below before running.

Run modes:
    Set RUN_MODE to "RAW", then "DETRENDED", and finally "PLOT".

Run:
    python scripts/03_figure1_t2m_composites.py
"""

import gc
from pathlib import Path

import cartopy.crs as ccrs
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import xarray as xr
from cartopy.util import add_cyclic_point
from matplotlib.colors import TwoSlopeNorm
from scipy.stats import ttest_1samp

plt.rcParams["font.family"] = "Arial"
mpl.rcParams["hatch.linewidth"] = 0.5
mpl.rcParams["hatch.color"] = "black"

# ---------------------------------------------------------------------
# User configuration
# ---------------------------------------------------------------------
RUN_MODE = "PLOT"  # Choose: "RAW", "DETRENDED", or "PLOT"
SSW_SOURCE = "SEAS5"  # Choose: "SEAS5" or "ERA5"

# Replace these placeholders with local paths before running.
SEAS5_SSW_CSV_PATH = Path(
    "path/to/analysis_results/"
    "SEAS5_first25members_SSW_dates_NDJFM_events_only_1981_2024.csv"
)
ERA5_SSW_CSV_PATH = Path(
    "path/to/analysis_results/"
    "ERA5_SSW_dates_10hPa_NDJFM_events_only_1940_2024.csv"
)
T2M_DIR = Path("path/to/SEAS5/t2m_daily")

# Generated outputs are saved here.
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_YEAR = 1981
END_YEAR = 2024
N_MEMBERS = 25

# Baseline climatology period.
BASELINE_START = 1981
BASELINE_END = 2010

LAT_THRESHOLD = 20
ALPHA_SIG = 0.05
T2M_VAR_CANDIDATES = ("2m_temperature",)

# Start lag, end lag, and display label.
COMBINED_WINDOW = (15, 59, "day 15 - day 59")

REGION_BOXES = {
    "NorthAmerica": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 220,
        "lon_max": 300,
    },
    "Europe": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 0,
        "lon_max": 40,
    },
    "Siberia": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 60,
        "lon_max": 120,
    },
}

DECADE_PERIODS = [
    (1981, 1990, "1981-1990"),
    (1991, 2000, "1991-2000"),
    (2001, 2010, "2001-2010"),
    (2011, 2020, "2011-2020"),
    (2021, 2024, "2021-2024"),
]

NPZ_RAW = OUTPUT_DIR / (
    f"fig1_SEAS5_SSW_T2m_combined_raw_day15_59_"
    f"10yr_{BASELINE_END}.npz"
)
NPZ_DET = OUTPUT_DIR / (
    f"fig1_SEAS5_SSW_T2m_combined_detrended_day15_59_"
    f"10yr_{BASELINE_END}.npz"
)
PNG_OUT = OUTPUT_DIR / f"fig1_SEAS5_SSW_T2m_10yr_{BASELINE_END}.pdf"


# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------
def get_var_name(ds, candidates):
    """Identify the 2-m temperature variable in a dataset."""
    for variable_name in candidates:
        if variable_name in ds.data_vars:
            return variable_name

    if len(ds.data_vars) == 1:
        return list(ds.data_vars)[0]

    raise ValueError(
        f"Cannot identify T2m variable. Available variables: "
        f"{list(ds.data_vars)}"
    )


def get_lat_lon_dim_names(da):
    """Return latitude and longitude dimension names."""
    lat_candidates = [dim for dim in da.dims if "lat" in dim.lower()]
    lon_candidates = [dim for dim in da.dims if "lon" in dim.lower()]

    if not lat_candidates:
        raise ValueError(f"Latitude dimension not found: {da.dims}")
    if not lon_candidates:
        raise ValueError(f"Longitude dimension not found: {da.dims}")

    return lat_candidates[0], lon_candidates[0]


def get_time_dim_name(da):
    """Return the time dimension name."""
    for name in ("valid_time", "time", "forecast_period"):
        if name in da.dims:
            return name

    raise ValueError(
        f"Time dimension not found. Dimensions: {da.dims}; "
        f"coordinates: {list(da.coords)}"
    )


def ensure_member_dim_first(da):
    """Move the ensemble-member dimension to the first position."""
    if "number" not in da.dims:
        raise ValueError(f"Missing ensemble-member dimension 'number': {da.dims}")

    return da.transpose("number", *[dim for dim in da.dims if dim != "number"])


def safe_member_label(number_coord, index):
    """Return an integer member label where possible."""
    try:
        return int(number_coord[index])
    except (TypeError, ValueError):
        return index + 1


def month_day_key(timestamp):
    """Return calendar date as MM-DD."""
    timestamp = pd.Timestamp(timestamp)
    return f"{timestamp.month:02d}-{timestamp.day:02d}"


def convert_lon_360_to_180(longitude):
    """Convert a longitude from 0-360 to -180-180 if needed."""
    return longitude - 360 if longitude > 180 else longitude


def add_region_boxes(ax):
    """Draw boxes for the three regional averages."""
    for region_box in REGION_BOXES.values():
        lon_min = convert_lon_360_to_180(region_box["lon_min"])
        lon_max = convert_lon_360_to_180(region_box["lon_max"])

        edges = [
            (
                [lon_min, lon_max],
                [region_box["lat_min"], region_box["lat_min"]],
            ),
            (
                [lon_min, lon_max],
                [region_box["lat_max"], region_box["lat_max"]],
            ),
            (
                [lon_min, lon_min],
                [region_box["lat_min"], region_box["lat_max"]],
            ),
            (
                [lon_max, lon_max],
                [region_box["lat_min"], region_box["lat_max"]],
            ),
        ]

        for x_values, y_values in edges:
            ax.plot(
                x_values,
                y_values,
                color="black",
                lw=1.4,
                transform=ccrs.PlateCarree(),
                zorder=6,
            )


# ---------------------------------------------------------------------
# SSW events
# ---------------------------------------------------------------------
def read_ssw_events():
    """Read SSW dates and return event records by year and member."""
    if SSW_SOURCE.upper() == "SEAS5":
        if not SEAS5_SSW_CSV_PATH.exists():
            raise FileNotFoundError(
                f"SEAS5 SSW-event CSV was not found:\n"
                f"  {SEAS5_SSW_CSV_PATH}\n\n"
                "Run 02_seas5_ssw_dates.py first or update "
                "SEAS5_SSW_CSV_PATH."
            )

        df = pd.read_csv(SEAS5_SSW_CSV_PATH)

        required_columns = ("init_year", "member", "ssw_date")
        for column in required_columns:
            if column not in df.columns:
                raise ValueError(f"SEAS5 SSW CSV missing column: {column}")

        df["ssw_date"] = pd.to_datetime(df["ssw_date"], errors="coerce")
        df = df.dropna(subset=["ssw_date"]).copy()

        df = df[
            (df["init_year"] >= START_YEAR)
            & (df["init_year"] <= END_YEAR)
        ].copy()

        df["member"] = df["member"].astype(int)

        df = df.sort_values(
            ["init_year", "member", "ssw_date"]
        ).reset_index(drop=True)

        print(f"Loaded SEAS5 SSW events: {len(df)}")
        return df

    if SSW_SOURCE.upper() == "ERA5":
        if not ERA5_SSW_CSV_PATH.exists():
            raise FileNotFoundError(
                f"ERA5 SSW-event CSV was not found:\n"
                f"  {ERA5_SSW_CSV_PATH}\n\n"
                "Run 01_era5_ssw_dates.py first or update "
                "ERA5_SSW_CSV_PATH."
            )

        era5_df = pd.read_csv(ERA5_SSW_CSV_PATH)

        required_columns = ("init_year", "ssw_date")
        for column in required_columns:
            if column not in era5_df.columns:
                raise ValueError(f"ERA5 SSW CSV missing column: {column}")

        era5_df["ssw_date"] = pd.to_datetime(
            era5_df["ssw_date"],
            errors="coerce",
        )
        era5_df = era5_df.dropna(subset=["ssw_date"]).copy()

        era5_df = era5_df[
            (era5_df["init_year"] >= START_YEAR)
            & (era5_df["init_year"] <= END_YEAR)
        ].copy()

        records = []

        for _, row in era5_df.iterrows():
            for member in range(N_MEMBERS):
                records.append(
                    {
                        "init_year": int(row["init_year"]),
                        "member": member,
                        "ssw_date": pd.Timestamp(row["ssw_date"]),
                    }
                )

        df = pd.DataFrame(records)

        if df.empty:
            raise RuntimeError("No ERA5 SSW events were available.")

        df = df.sort_values(
            ["init_year", "member", "ssw_date"]
        ).reset_index(drop=True)

        print(f"Loaded ERA5 events expanded to SEAS5 members: {len(df)}")
        return df

    raise ValueError("SSW_SOURCE must be either 'SEAS5' or 'ERA5'.")


# ---------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------
def load_one_year(year):
    """Load one SEAS5 daily T2m file and standardize its dimensions."""
    input_file = T2M_DIR / (
        f"SEAS5_2mt_NH_{year}11_system51_m25_daily.nc"
    )

    if not input_file.exists():
        print(f"  Missing file: {input_file.name}")
        return None

    try:
        ds = xr.open_dataset(input_file)

        try:
            variable_name = get_var_name(ds, T2M_VAR_CANDIDATES)
            da = ds[variable_name].load()
        finally:
            ds.close()

        da = ensure_member_dim_first(da)
        da = da.isel(number=slice(0, N_MEMBERS))

        lat_name, lon_name = get_lat_lon_dim_names(da)
        time_name = get_time_dim_name(da)

        if da[lat_name].values[0] < da[lat_name].values[-1]:
            da = da.isel({lat_name: slice(None, None, -1)})

        original_lon = da[lon_name].values

        if np.nanmax(original_lon) > 180:
            converted_lon = np.where(
                original_lon > 180,
                original_lon - 360,
                original_lon,
            )
            sort_index = np.argsort(converted_lon)

            da = da.isel({lon_name: sort_index})
            da = da.assign_coords({lon_name: converted_lon[sort_index]})

        lat_values = da[lat_name].values.copy()
        lon_values = da[lon_name].values.copy()
        times = pd.to_datetime(da[time_name].values)

        member_labels = [
            safe_member_label(da["number"].values, index)
            for index in range(da.sizes["number"])
        ]

        t2m_values = da.values.astype(np.float32)

        monthday = np.array([month_day_key(time) for time in times])
        member_to_index = {
            member: index
            for index, member in enumerate(member_labels)
        }
        time_to_index = {
            pd.Timestamp(time): index
            for index, time in enumerate(times)
        }

        print(f"  Loaded: {input_file.name}; shape={t2m_values.shape}")

        return (
            t2m_values,
            times,
            monthday,
            member_labels,
            member_to_index,
            time_to_index,
            lat_values,
            lon_values,
        )

    except Exception as error:
        print(f"  Failed to load year {year}: {error}")
        gc.collect()
        return None


# ---------------------------------------------------------------------
# Baseline climatology
# ---------------------------------------------------------------------
def build_baseline_climatology():
    """Build an 11-day-smoothed ensemble-mean daily climatology."""
    print(
        f"\nBuilding baseline climatology: "
        f"{BASELINE_START}-{BASELINE_END}"
    )

    day_of_year_fields = {}
    lat_values = None
    lon_values = None

    for year in range(BASELINE_START, BASELINE_END + 1):
        result = load_one_year(year)

        if result is None:
            continue

        (
            t2m_values,
            times,
            _,
            _,
            _,
            _,
            year_lat_values,
            year_lon_values,
        ) = result

        if lat_values is None:
            lat_values = year_lat_values
            lon_values = year_lon_values

        ensemble_mean = t2m_values.mean(axis=0)
        day_of_years = pd.to_datetime(times).dayofyear.values

        for index, day_of_year in enumerate(day_of_years):
            day_of_year_fields.setdefault(day_of_year, []).append(
                ensemble_mean[index].astype(np.float32)
            )

        del t2m_values, times, ensemble_mean, day_of_years
        gc.collect()

    if not day_of_year_fields or lat_values is None or lon_values is None:
        raise RuntimeError(
            "No baseline data were loaded. Check T2M_DIR and "
            "BASELINE_START/BASELINE_END."
        )

    print("  Building raw daily climatology")

    n_lat = len(lat_values)
    n_lon = len(lon_values)
    n_days = 366

    climatology_raw = np.full(
        (n_days, n_lat, n_lon),
        np.nan,
        dtype=np.float32,
    )

    for day_of_year, fields in day_of_year_fields.items():
        climatology_raw[day_of_year - 1] = np.nanmean(
            np.stack(fields, axis=0),
            axis=0,
        )

    del day_of_year_fields
    gc.collect()

    print("  Applying 11-day circular smoothing")

    window = 11
    padding = window // 2

    climatology_padded = np.concatenate(
        [
            climatology_raw[-padding:],
            climatology_raw,
            climatology_raw[:padding],
        ],
        axis=0,
    )

    climatology_smoothed = np.full_like(climatology_raw, np.nan)

    for index in range(n_days):
        climatology_smoothed[index] = np.nanmean(
            climatology_padded[index:index + window],
            axis=0,
        )

    del climatology_padded, climatology_raw
    gc.collect()

    baseline_climatology = {}

    for date in pd.date_range("2001-01-01", "2001-12-31"):
        key = month_day_key(date)
        baseline_climatology[key] = climatology_smoothed[
            date.dayofyear - 1
        ]

    del climatology_smoothed
    gc.collect()

    print(
        f"  Baseline climatology complete: "
        f"{len(baseline_climatology)} calendar-day fields"
    )

    return baseline_climatology, lat_values, lon_values


def build_anomaly_field(t2m_values, monthday, baseline_climatology):
    """Calculate daily T2m anomalies from the baseline climatology."""
    _, n_time, n_lat, n_lon = t2m_values.shape

    climatology = np.full(
        (n_time, n_lat, n_lon),
        np.nan,
        dtype=np.float32,
    )

    for index, key in enumerate(monthday):
        if key in baseline_climatology:
            climatology[index] = baseline_climatology[key]

    anomalies = t2m_values - climatology[None, :, :, :]

    del climatology
    return anomalies


# ---------------------------------------------------------------------
# Composite calculations
# ---------------------------------------------------------------------
def extract_samples_from_year(
    year,
    anomalies,
    member_to_index,
    time_to_index,
    ssw_df,
    day_start,
    day_end,
    period_samples,
):
    """Extract one day-15 to day-59 mean field for every valid SSW event."""
    n_time = anomalies.shape[1]

    period_label = None

    for start_year, end_year, label in DECADE_PERIODS:
        if start_year <= year <= end_year:
            period_label = label
            break

    if period_label is None:
        return

    events_this_year = ssw_df[
        ssw_df["init_year"] == year
    ]

    for _, row in events_this_year.iterrows():
        member = int(row["member"])
        onset_date = pd.Timestamp(row["ssw_date"]).normalize()

        if member not in member_to_index:
            continue

        if onset_date not in time_to_index:
            continue

        member_index = member_to_index[member]
        onset_index = time_to_index[onset_date]

        start_index = onset_index + day_start
        end_index = onset_index + day_end + 1

        if start_index < 0 or end_index > n_time:
            continue

        event_mean = np.nanmean(
            anomalies[member_index, start_index:end_index],
            axis=0,
        ).astype(np.float32)

        period_samples[period_label].append(event_mean)


def calculate_composites(
    ssw_df,
    baseline_climatology,
    lat_values,
    lon_values,
    detrend=False,
):
    """Calculate raw or detrended SSW-composite fields."""
    mode_name = "detrended" if detrend else "raw"

    print("\n" + "=" * 70)
    print(f"Calculating {mode_name} composites")
    print("=" * 70)

    n_lat = len(lat_values)
    n_lon = len(lon_values)
    day_start, day_end, _ = COMBINED_WINDOW

    period_samples = {
        label: []
        for _, _, label in DECADE_PERIODS
    }

    trend_parameters = None
    trend_reference_year = None

    if detrend:
        print("  Pass 1 of 2: calculating daily trend parameters")

        calendar_day_entries = {}
        usable_years = []

        for year in range(START_YEAR, END_YEAR + 1):
            result = load_one_year(year)

            if result is None:
                continue

            t2m_values, _, monthday, _, _, _, _, _ = result

            anomalies = build_anomaly_field(
                t2m_values,
                monthday,
                baseline_climatology,
            )
            ensemble_mean = anomalies.mean(axis=0)

            for index, key in enumerate(monthday):
                calendar_day_entries.setdefault(key, []).append(
                    (year, ensemble_mean[index].astype(np.float32))
                )

            usable_years.append(year)

            del t2m_values, anomalies, ensemble_mean, monthday
            gc.collect()

        if not usable_years:
            raise RuntimeError("No SEAS5 data available for detrending.")

        trend_reference_year = float(np.mean(usable_years))
        trend_parameters = {}

        for key, entries in calendar_day_entries.items():
            if len(entries) < 2:
                continue

            years = np.array(
                [entry[0] for entry in entries],
                dtype=np.float64,
            )
            centered_years = years - years.mean()

            fields = np.stack(
                [entry[1] for entry in entries],
                axis=0,
            ).astype(np.float64)

            denominator = np.sum(centered_years ** 2)

            if denominator == 0:
                continue

            slope = (
                centered_years[:, None, None] * fields
            ).sum(axis=0) / denominator

            intercept_at_mean_year = fields.mean(axis=0)

            trend_parameters[key] = (
                intercept_at_mean_year.astype(np.float32),
                slope.astype(np.float32),
            )

            del years, centered_years, fields, slope, intercept_at_mean_year

        del calendar_day_entries
        gc.collect()

        print(
            f"  Trend parameters calculated for "
            f"{len(trend_parameters)} calendar days"
        )

        print("  Pass 2 of 2: extracting detrended composites")

    for year in range(START_YEAR, END_YEAR + 1):
        result = load_one_year(year)

        if result is None:
            continue

        (
            t2m_values,
            _,
            monthday,
            _,
            member_to_index,
            time_to_index,
            _,
            _,
        ) = result

        anomalies = build_anomaly_field(
            t2m_values,
            monthday,
            baseline_climatology,
        )

        if detrend:
            for index, key in enumerate(monthday):
                if key not in trend_parameters:
                    continue

                intercept_at_mean_year, slope = trend_parameters[key]
                trend_value = (
                    intercept_at_mean_year
                    + slope * (year - trend_reference_year)
                )

                anomalies[:, index] -= trend_value[None, :, :]

        extract_samples_from_year(
            year=year,
            anomalies=anomalies,
            member_to_index=member_to_index,
            time_to_index=time_to_index,
            ssw_df=ssw_df,
            day_start=day_start,
            day_end=day_end,
            period_samples=period_samples,
        )

        del t2m_values, anomalies, monthday, member_to_index, time_to_index
        gc.collect()

    if detrend:
        del trend_parameters
        gc.collect()

    results = {}

    for _, _, label in DECADE_PERIODS:
        samples = period_samples[label]

        if samples:
            sample_stack = np.stack(samples, axis=0).astype(np.float32)
            composite = np.nanmean(sample_stack, axis=0).astype(np.float32)

            if sample_stack.shape[0] >= 2:
                _, p_values = ttest_1samp(
                    sample_stack,
                    popmean=0.0,
                    axis=0,
                    nan_policy="omit",
                )

                not_significant = (
                    (~np.isfinite(p_values))
                    | (p_values >= ALPHA_SIG)
                ).astype(np.int8)

                del p_values

            else:
                not_significant = np.ones(
                    (n_lat, n_lon),
                    dtype=np.int8,
                )

            sample_count = sample_stack.shape[0]

            del sample_stack

        else:
            composite = np.full(
                (n_lat, n_lon),
                np.nan,
                dtype=np.float32,
            )
            not_significant = np.ones(
                (n_lat, n_lon),
                dtype=np.int8,
            )
            sample_count = 0

        results[label] = {
            "composite": composite,
            "count": sample_count,
            "notsig": not_significant,
        }

        print(f"  Period {label}: {sample_count} event samples")

    del period_samples
    gc.collect()

    return results


# ---------------------------------------------------------------------
# Cache I/O
# ---------------------------------------------------------------------
def save_results(npz_path, results, lat_values, lon_values):
    """Save composite fields and metadata in a compressed NPZ archive."""
    save_dict = {
        "lat": lat_values,
        "lon": lon_values,
    }

    for _, _, label in DECADE_PERIODS:
        save_dict[f"{label}__comp"] = results[label]["composite"]
        save_dict[f"{label}__count"] = np.array(results[label]["count"])
        save_dict[f"{label}__notsig"] = results[label]["notsig"]

    np.savez(npz_path, **save_dict)
    print(f"Saved cache: {npz_path}")


def load_results(npz_path):
    """Load a saved composite archive."""
    if not npz_path.exists():
        raise FileNotFoundError(
            f"Required cache was not found:\n  {npz_path}\n\n"
            "Run first with RUN_MODE='RAW' or RUN_MODE='DETRENDED'."
        )

    data = np.load(npz_path, allow_pickle=False)

    lat_values = data["lat"]
    lon_values = data["lon"]
    results = {}

    for _, _, label in DECADE_PERIODS:
        results[label] = {
            "composite": data[f"{label}__comp"],
            "count": int(data[f"{label}__count"]),
            "notsig": data[f"{label}__notsig"],
        }

    print(f"Loaded cache: {npz_path}")

    return results, lat_values, lon_values


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------
def plot_combined_figure(raw_results, detrended_results, lat_values, lon_values):
    """Plot the Figure 1 raw and detrended T2m composite panels."""
    print(f"\nCreating figure: {PNG_OUT}")

    lat_full = lat_values.copy()
    lon = lon_values.copy()
    n_lat = len(lat_values)

    lat_threshold_index = np.argmax(lat_full < LAT_THRESHOLD)

    if lat_threshold_index == 0 and lat_full[0] < LAT_THRESHOLD:
        lat_threshold_index = n_lat

    norm = TwoSlopeNorm(vmin=-2, vcenter=0.0, vmax=2)
    n_rows = len(DECADE_PERIODS)
    n_cols = 2

    fig = plt.figure(figsize=(13, 2.5 * n_rows))
    contour_reference = None

    panel_labels = [
        "(a)", "(b)", "(c)", "(d)", "(e)",
        "(f)", "(g)", "(h)", "(i)", "(j)",
    ]

    for row_index, (_, _, period_label) in enumerate(DECADE_PERIODS):
        panel_sources = (
            (raw_results, "Raw T2m"),
            (detrended_results, "Detrended T2m"),
        )

        for column_index, (results, column_title) in enumerate(panel_sources):
            ax = fig.add_subplot(
                n_rows,
                n_cols,
                row_index * n_cols + column_index + 1,
                projection=ccrs.PlateCarree(),
            )

            composite = results[period_label]["composite"].copy()
            composite[lat_threshold_index:] = np.nan

            cyclic_composite, cyclic_lon = add_cyclic_point(
                composite,
                coord=lon,
            )

            lon_grid, lat_grid = np.meshgrid(cyclic_lon, lat_full)

            contour_reference = ax.pcolormesh(
                lon_grid,
                lat_grid,
                cyclic_composite,
                transform=ccrs.PlateCarree(),
                cmap=plt.cm.RdBu_r,
                norm=norm,
                shading="auto",
            )

            ax.coastlines(linewidth=0.8)
            ax.set_extent(
                [-180, 180, LAT_THRESHOLD, 90],
                crs=ccrs.PlateCarree(),
            )

            gridlines = ax.gridlines(
                draw_labels=True,
                linestyle="--",
                alpha=0.4,
                linewidth=0.4,
            )

            gridlines.xlocator = plt.MultipleLocator(60)
            gridlines.ylocator = ticker.FixedLocator([30, 50, 70])
            gridlines.top_labels = False
            gridlines.right_labels = False
            gridlines.left_labels = column_index == 0
            gridlines.bottom_labels = row_index == n_rows - 1
            gridlines.xlabel_style = {"size": 10}
            gridlines.ylabel_style = {"size": 10}

            if row_index == 0:
                add_region_boxes(ax)

            not_significant = results[period_label]["notsig"].astype(float)
            not_significant[lat_threshold_index:] = np.nan
            not_significant[not_significant == 0] = np.nan

            cyclic_not_significant, _ = add_cyclic_point(
                not_significant,
                coord=lon,
            )

            ax.contourf(
                lon_grid,
                lat_grid,
                cyclic_not_significant,
                levels=[0.5, 1.5],
                hatches=["////"],
                colors="none",
                transform=ccrs.PlateCarree(),
            )

            panel_index = row_index * n_cols + column_index

            ax.text(
                0.02,
                0.98,
                panel_labels[panel_index],
                transform=ax.transAxes,
                ha="left",
                va="top",
                fontsize=12,
                fontweight="bold",
                bbox={
                    "facecolor": "white",
                    "edgecolor": "none",
                    "alpha": 0.75,
                    "pad": 1.5,
                },
                zorder=10,
            )

            if row_index == 0:
                ax.text(
                    0.5,
                    1.25,
                    column_title,
                    transform=ax.transAxes,
                    ha="center",
                    va="bottom",
                    fontsize=13,
                    fontweight="bold",
                )

            event_count = results[period_label]["count"]

            ax.set_title(
                f"{period_label} (n={event_count})",
                fontsize=12,
                fontweight="bold",
                pad=4,
            )

    fig.subplots_adjust(right=0.88, hspace=-0.6, wspace=0.08)

    colorbar_axis = fig.add_axes([0.90, 0.30, 0.015, 0.40])
    colorbar = fig.colorbar(contour_reference, cax=colorbar_axis)
    colorbar.set_label(
        "T2m anomaly (K)",
        fontsize=12,
        fontweight="bold",
    )

    plt.savefig(PNG_OUT, dpi=300, bbox_inches="tight")
    plt.close(fig)

    gc.collect()

    print(f"Saved figure: {PNG_OUT}")


# ---------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------
def main():
    """Run the selected Figure 1 workflow."""
    run_mode = RUN_MODE.upper()

    if run_mode not in ("RAW", "DETRENDED", "PLOT"):
        raise ValueError(
            "RUN_MODE must be 'RAW', 'DETRENDED', or 'PLOT'."
        )

    print("=" * 70)
    print(f"SSW source: {SSW_SOURCE}")
    print(f"Run mode: {run_mode}")
    print(f"Output directory: {OUTPUT_DIR}")
    print("=" * 70)

    ssw_df = read_ssw_events()

    if run_mode == "PLOT":
        raw_results, lat_values, lon_values = load_results(NPZ_RAW)
        detrended_results, _, _ = load_results(NPZ_DET)

        plot_combined_figure(
            raw_results,
            detrended_results,
            lat_values,
            lon_values,
        )

        del raw_results, detrended_results, lat_values, lon_values, ssw_df
        gc.collect()

        print("\nFinished.")
        return

    baseline_climatology, lat_values, lon_values = (
        build_baseline_climatology()
    )

    if run_mode == "RAW":
        if NPZ_RAW.exists():
            print(f"\nRaw cache already exists: {NPZ_RAW}")
        else:
            raw_results = calculate_composites(
                ssw_df,
                baseline_climatology,
                lat_values,
                lon_values,
                detrend=False,
            )

            save_results(
                NPZ_RAW,
                raw_results,
                lat_values,
                lon_values,
            )

            del raw_results
            gc.collect()

        print("\nRAW workflow complete.")
        print("Set RUN_MODE = 'DETRENDED' and run the script again.")

    elif run_mode == "DETRENDED":
        if NPZ_DET.exists():
            print(f"\nDetrended cache already exists: {NPZ_DET}")
        else:
            detrended_results = calculate_composites(
                ssw_df,
                baseline_climatology,
                lat_values,
                lon_values,
                detrend=True,
            )

            save_results(
                NPZ_DET,
                detrended_results,
                lat_values,
                lon_values,
            )

            del detrended_results
            gc.collect()

        print("\nDETRENDED workflow complete.")
        print("Set RUN_MODE = 'PLOT' and run the script again.")

    del ssw_df, baseline_climatology, lat_values, lon_values
    gc.collect()

    print("\nFinished.")


if __name__ == "__main__":
    main()
