# -*- coding: utf-8 -*-
"""
Reproduce Figure 2: lagged regional SEAS5 2-m temperature anomalies
relative to stratospheric sudden warming (SSW) onset.

The script calculates cosine-latitude-weighted 2-m temperature anomaly
composites from lag day -20 to +60 for North America, Europe, and East
Asia. Raw and linearly detrended anomalies are compared between
1981-1990 and 2015-2024.

Input:
    - Daily SEAS5 2-m temperature NetCDF files.
    - A SEAS5 SSW-event CSV generated by 02_seas5_ssw_dates.py.
    - Optionally, an ERA5 SSW-event CSV generated by
      01_era5_ssw_dates.py.

Output:
    - An NPZ cache containing lag-composite data.
    - A PDF figure saved in OUTPUT_DIR.

Raw ERA5 and SEAS5 data are not redistributed with this repository.
Update the paths below before running.

Run:
    python scripts/04_figure2_t2m_lag_composites.py
"""

import gc
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
from scipy.stats import sem

plt.rcParams["font.family"] = "Arial"

# ---------------------------------------------------------------------
# User configuration
# ---------------------------------------------------------------------
SSW_SOURCE = "SEAS5"  # Choose: "SEAS5" or "ERA5"

# Replace these placeholders with local paths before running.
SEAS5_SSW_CSV_PATH = Path(
    "path/to/analysis_results/"
    "SEAS5_first25members_SSW_dates_NDJFM_events_only_1981_2024.csv"
)
ERA5_SSW_CSV_PATH = Path(
    "path/to/analysis_results/"
    "ERA5_SSW_dates_10hPa_NDJFM_events_only_1940_2024.csv"
)
T2M_DAILY_DIR = Path("path/to/SEAS5/t2m_daily")

# Generated cache and figure are saved here.
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_YEAR = 1981
END_YEAR = 2024
N_MEMBERS = 25
BASELINE_START = 1981
BASELINE_END = 2010

T2M_VAR_CANDIDATES = ("2m_temperature",)

REGION_BOXES = {
    "NorthAmerica": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": -140,
        "lon_max": -60,
    },
    "Europe": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 0,
        "lon_max": 40,
    },
    "EastAsia": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 60,
        "lon_max": 120,
    },
}

REGION_TITLES = {
    "NorthAmerica": "North America",
    "Europe": "Europe",
    "EastAsia": "East Asia",
}

REGION_ORDER = ("NorthAmerica", "Europe", "EastAsia")

# Retained for consistency with the original analysis configuration.
SLIDING_WINDOW = 10

# Retained for provenance; not used in this lag-composite figure.
TIME_WINDOWS_CODE1 = (
    (0, 15, "day 0 to +15"),
    (15, 30, "day +15 to +30"),
    (30, 45, "day +30 to +45"),
    (45, 60, "day +45 to +60"),
)

LAGS = np.arange(-20, 61)

PERIOD1 = tuple(range(1981, 1991))
PERIOD2 = tuple(range(2015, 2025))

NPZ_LAG = OUTPUT_DIR / (
    f"fig2_lag_combined_cache_{BASELINE_END}_m20to60.npz"
)
PNG_OUT_LAG = OUTPUT_DIR / (
    f"fig2_SEAS5_SSW_T2m_lag_{BASELINE_END}.pdf"
)


# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------
def get_var_name(ds, candidates):
    """Identify the 2-m temperature variable in a dataset."""
    for variable_name in candidates:
        if variable_name in ds.data_vars:
            return variable_name

    if len(ds.data_vars) == 1:
        return list(ds.data_vars)[0]

    raise ValueError(
        f"Cannot identify T2m variable. "
        f"Available variables: {list(ds.data_vars)}"
    )


def get_lat_lon_dim_names(da):
    """Return latitude and longitude dimension names."""
    lat_candidates = [dim for dim in da.dims if "lat" in dim.lower()]
    lon_candidates = [dim for dim in da.dims if "lon" in dim.lower()]

    if not lat_candidates:
        raise ValueError(f"Latitude dimension not found: {da.dims}")
    if not lon_candidates:
        raise ValueError(f"Longitude dimension not found: {da.dims}")

    return lat_candidates[0], lon_candidates[0]


def get_time_dim_name(da):
    """Return the time dimension name."""
    for name in ("valid_time", "time"):
        if name in da.dims:
            return name

    raise ValueError(f"Time dimension not found: {da.dims}")


def safe_member_label(number_coord, index):
    """Return an integer member label where possible."""
    try:
        return int(number_coord[index])
    except (TypeError, ValueError):
        return index + 1


def month_day_key(timestamp):
    """Return a calendar-day key in MM-DD format."""
    timestamp = pd.Timestamp(timestamp)
    return f"{timestamp.month:02d}-{timestamp.day:02d}"


def cosine_weighted_region_mean(field_2d, lat_values, lon_values, region_box):
    """Calculate a cosine-latitude-weighted regional mean."""
    lat_mask = (
        (lat_values >= region_box["lat_min"])
        & (lat_values <= region_box["lat_max"])
    )
    lon_mask = (
        (lon_values >= region_box["lon_min"])
        & (lon_values <= region_box["lon_max"])
    )

    if not np.any(lat_mask) or not np.any(lon_mask):
        return np.nan

    subset = field_2d[np.ix_(lat_mask, lon_mask)]

    latitude_weights = np.cos(np.deg2rad(lat_values[lat_mask]))
    weights_2d = latitude_weights[:, None] * np.ones(lon_mask.sum())

    valid = np.isfinite(subset)

    if not np.any(valid):
        return np.nan

    return float(
        np.nansum(subset * weights_2d * valid)
        / np.nansum(weights_2d * valid)
    )


# ---------------------------------------------------------------------
# Daily SEAS5 data loading
# ---------------------------------------------------------------------
def load_one_year_daily(year):
    """Load and standardize one daily SEAS5 2-m temperature file."""
    input_file = T2M_DAILY_DIR / (
        f"SEAS5_2mt_NH_{year}11_system51_m25_daily.nc"
    )

    if not input_file.exists():
        print(f"  Missing input file: {input_file.name}")
        return None

    try:
        ds = xr.open_dataset(input_file)

        try:
            variable_name = get_var_name(ds, T2M_VAR_CANDIDATES)
            da = ds[variable_name].load()
        finally:
            ds.close()

        if "number" not in da.dims:
            raise ValueError(
                f"Ensemble-member dimension 'number' not found: {da.dims}"
            )

        da = da.transpose(
            "number",
            *[dimension for dimension in da.dims if dimension != "number"],
        )
        da = da.isel(number=slice(0, N_MEMBERS))

        lat_name, lon_name = get_lat_lon_dim_names(da)
        time_name = get_time_dim_name(da)

        if da[lat_name].values[0] < da[lat_name].values[-1]:
            da = da.isel({lat_name: slice(None, None, -1)})

        original_lon = da[lon_name].values

        if np.nanmax(original_lon) > 180:
            converted_lon = np.where(
                original_lon > 180,
                original_lon - 360,
                original_lon,
            )
            sort_index = np.argsort(converted_lon)

            da = da.isel({lon_name: sort_index})
            da = da.assign_coords({lon_name: converted_lon[sort_index]})

        times = pd.to_datetime(da[time_name].values).normalize()

        member_labels = [
            safe_member_label(da["number"].values, index)
            for index in range(da.sizes["number"])
        ]

        t2m_values = da.values.astype(np.float32)
        lat_values = da[lat_name].values.copy()
        lon_values = da[lon_name].values.copy()

        print(f"  Loaded: {input_file.name}; shape={t2m_values.shape}")

        return {
            "t2m": t2m_values,
            "times": times,
            "monthday": np.array([month_day_key(time) for time in times]),
            "member_labels": member_labels,
            "member_to_idx": {
                member: index
                for index, member in enumerate(member_labels)
            },
            "time_to_idx": {
                pd.Timestamp(time): index
                for index, time in enumerate(times)
            },
            "lat_vals": lat_values,
            "lon_vals": lon_values,
        }

    except Exception as error:
        print(f"  Failed to load initialization year {year}: {error}")
        gc.collect()
        return None


# ---------------------------------------------------------------------
# SSW-event loading
# ---------------------------------------------------------------------
def read_ssw_events():
    """Read SEAS5 or ERA5 SSW dates."""
    source = SSW_SOURCE.upper()

    if source == "SEAS5":
        if not SEAS5_SSW_CSV_PATH.exists():
            raise FileNotFoundError(
                f"SEAS5 SSW-event CSV was not found:\n"
                f"  {SEAS5_SSW_CSV_PATH}\n\n"
                "Run 02_seas5_ssw_dates.py first or update "
                "SEAS5_SSW_CSV_PATH."
            )

        df = pd.read_csv(SEAS5_SSW_CSV_PATH)

        required_columns = ("init_year", "member", "ssw_date")
        for column in required_columns:
            if column not in df.columns:
                raise ValueError(f"SEAS5 SSW CSV missing column: {column}")

        df["ssw_date"] = pd.to_datetime(
            df["ssw_date"],
            errors="coerce",
        ).dt.normalize()

        df = df.dropna(subset=["ssw_date"]).copy()

        df = df[
            (df["init_year"] >= START_YEAR)
            & (df["init_year"] <= END_YEAR)
        ].copy()

        df["member"] = df["member"].astype(int)

        df = df.sort_values(
            ["init_year", "member", "ssw_date"]
        ).reset_index(drop=True)

        print(f"Loaded SEAS5 SSW events: {len(df)}")
        return df

    if source == "ERA5":
        if not ERA5_SSW_CSV_PATH.exists():
            raise FileNotFoundError(
                f"ERA5 SSW-event CSV was not found:\n"
                f"  {ERA5_SSW_CSV_PATH}\n\n"
                "Run 01_era5_ssw_dates.py first or update "
                "ERA5_SSW_CSV_PATH."
            )

        era5_df = pd.read_csv(ERA5_SSW_CSV_PATH)

        required_columns = ("init_year", "ssw_date")
        for column in required_columns:
            if column not in era5_df.columns:
                raise ValueError(f"ERA5 SSW CSV missing column: {column}")

        era5_df["ssw_date"] = pd.to_datetime(
            era5_df["ssw_date"],
            errors="coerce",
        ).dt.normalize()

        era5_df = era5_df.dropna(subset=["ssw_date"]).copy()

        era5_df = era5_df[
            (era5_df["init_year"] >= START_YEAR)
            & (era5_df["init_year"] <= END_YEAR)
        ].copy()

        records = []

        for _, row in era5_df.iterrows():
            for member in range(N_MEMBERS):
                records.append(
                    {
                        "init_year": int(row["init_year"]),
                        "member": member,
                        "ssw_date": pd.Timestamp(
                            row["ssw_date"]
                        ).normalize(),
                    }
                )

        df = pd.DataFrame(records)

        if df.empty:
            raise RuntimeError("No ERA5 SSW events are available.")

        df = df.sort_values(
            ["init_year", "member", "ssw_date"]
        ).reset_index(drop=True)

        print(f"Loaded ERA5 SSW events expanded to members: {len(df)}")
        return df

    raise ValueError("SSW_SOURCE must be either 'SEAS5' or 'ERA5'.")


# ---------------------------------------------------------------------
# Baseline and trends
# ---------------------------------------------------------------------
def build_baseline_climatology():
    """Build an 11-day-smoothed baseline daily climatology."""
    print(
        f"\nBuilding baseline climatology: "
        f"{BASELINE_START}-{BASELINE_END}"
    )

    day_of_year_fields = {}
    lat_values = None
    lon_values = None

    for year in range(BASELINE_START, BASELINE_END + 1):
        data = load_one_year_daily(year)

        if data is None:
            continue

        if lat_values is None:
            lat_values = data["lat_vals"]
            lon_values = data["lon_vals"]

        ensemble_mean = data["t2m"].mean(axis=0)
        day_of_years = pd.to_datetime(data["times"]).dayofyear.values

        for index, day_of_year in enumerate(day_of_years):
            day_of_year_fields.setdefault(day_of_year, []).append(
                ensemble_mean[index].astype(np.float32)
            )

        del data, ensemble_mean, day_of_years
        gc.collect()

    if not day_of_year_fields or lat_values is None or lon_values is None:
        raise RuntimeError(
            "No baseline data were loaded. Check T2M_DAILY_DIR and "
            "the baseline years."
        )

    n_lat = len(lat_values)
    n_lon = len(lon_values)

    climatology_raw = np.full(
        (366, n_lat, n_lon),
        np.nan,
        dtype=np.float32,
    )

    for day_of_year, fields in day_of_year_fields.items():
        climatology_raw[day_of_year - 1] = np.nanmean(
            np.stack(fields, axis=0),
            axis=0,
        )

    del day_of_year_fields
    gc.collect()

    print("  Applying 11-day circular smoothing")

    window = 11
    padding = window // 2

    climatology_padded = np.concatenate(
        [
            climatology_raw[-padding:],
            climatology_raw,
            climatology_raw[:padding],
        ],
        axis=0,
    )

    climatology_smoothed = np.full_like(climatology_raw, np.nan)

    for index in range(366):
        window_values = climatology_padded[index:index + window]

        if np.isfinite(window_values).any():
            climatology_smoothed[index] = np.nanmean(
                window_values,
                axis=0,
            )

    del climatology_padded, climatology_raw
    gc.collect()

    baseline_climatology = {}

    for date in pd.date_range("2001-01-01", "2001-12-31"):
        baseline_climatology[month_day_key(date)] = (
            climatology_smoothed[date.dayofyear - 1]
        )

    del climatology_smoothed
    gc.collect()

    print(f"  Baseline climatology complete: {len(baseline_climatology)} days")

    return baseline_climatology, lat_values, lon_values


def build_trend_params(baseline_climatology):
    """Calculate calendar-day trend parameters from ensemble-mean anomalies."""
    print("\nBuilding cross-year daily trend parameters")

    calendar_day_anomalies = {}

    for year in range(START_YEAR, END_YEAR + 1):
        data = load_one_year_daily(year)

        if data is None:
            continue

        ensemble_mean = data["t2m"].mean(axis=0)

        for index, timestamp in enumerate(data["times"]):
            key = (timestamp.month, timestamp.day)
            climatology_field = baseline_climatology.get(
                month_day_key(timestamp)
            )

            if climatology_field is None:
                continue

            anomaly = (
                ensemble_mean[index] - climatology_field
            ).astype(np.float32)

            calendar_day_anomalies.setdefault(key, []).append(
                (year, anomaly)
            )

        del data, ensemble_mean
        gc.collect()

    trend_params = {}

    for key, entries in calendar_day_anomalies.items():
        if len(entries) < 2:
            continue

        year_values = np.array(
            [entry[0] for entry in entries],
            dtype=np.float64,
        )
        centered_years = year_values - year_values.mean()
        denominator = np.sum(centered_years ** 2)

        if denominator < 1e-10:
            continue

        anomaly_stack = np.stack(
            [entry[1] for entry in entries],
            axis=0,
        ).astype(np.float64)

        slope = (
            centered_years[:, None, None] * anomaly_stack
        ).sum(axis=0) / denominator

        intercept_at_mean_year = anomaly_stack.mean(axis=0)

        trend_params[key] = (
            intercept_at_mean_year.astype(np.float32),
            slope.astype(np.float32),
            float(year_values.mean()),
        )

        del (
            year_values,
            centered_years,
            anomaly_stack,
            slope,
            intercept_at_mean_year,
        )

    del calendar_day_anomalies
    gc.collect()

    print(f"  Trend parameters created for {len(trend_params)} calendar days")

    return trend_params


# ---------------------------------------------------------------------
# Lag composites
# ---------------------------------------------------------------------
def build_lag_composites(
    ssw_df,
    baseline_climatology,
    trend_params,
    lat_values,
    lon_values,
):
    """Calculate raw and detrended regional lag composites."""
    print(f"\nBuilding lag composites from {LAGS[0]} to {LAGS[-1]} days")

    data_store = {
        tag: {
            region_name: {lag: [] for lag in LAGS}
            for region_name in REGION_ORDER
        }
        for tag in ("p1_raw", "p2_raw", "p1_det", "p2_det")
    }

    for year in range(START_YEAR, END_YEAR + 1):
        events_this_year = ssw_df[
            ssw_df["init_year"] == year
        ]

        if events_this_year.empty:
            continue

        data = load_one_year_daily(year)

        if data is None:
            continue

        t2m_values = data["t2m"]
        times = data["times"]
        member_to_index = data["member_to_idx"]
        time_to_index = data["time_to_idx"]

        n_time = t2m_values.shape[1]
        n_lat = t2m_values.shape[2]
        n_lon = t2m_values.shape[3]

        climatology = np.full(
            (n_time, n_lat, n_lon),
            np.nan,
            dtype=np.float32,
        )

        for index, timestamp in enumerate(times):
            climatology_field = baseline_climatology.get(
                month_day_key(timestamp)
            )

            if climatology_field is not None:
                climatology[index] = climatology_field

        raw_anomalies = t2m_values - climatology[None, :, :, :]
        detrended_anomalies = raw_anomalies.copy()

        for index, timestamp in enumerate(times):
            key = (timestamp.month, timestamp.day)
            coefficients = trend_params.get(key)

            if coefficients is None:
                continue

            intercept_at_mean_year, slope, mean_year = coefficients

            trend_value = (
                intercept_at_mean_year
                + slope * (year - mean_year)
            )

            detrended_anomalies[:, index] -= trend_value[None, :, :]

        del climatology
        gc.collect()

        in_period_1 = year in PERIOD1
        in_period_2 = year in PERIOD2

        for _, row in events_this_year.iterrows():
            member = int(row["member"])
            onset_date = pd.Timestamp(row["ssw_date"]).normalize()

            if member not in member_to_index:
                continue

            if onset_date not in time_to_index:
                continue

            member_index = member_to_index[member]
            onset_index = time_to_index[onset_date]

            for lag in LAGS:
                time_index = onset_index + lag

                if time_index < 0 or time_index >= n_time:
                    continue

                raw_field = raw_anomalies[member_index, time_index]
                detrended_field = detrended_anomalies[member_index, time_index]

                for region_name, region_box in REGION_BOXES.items():
                    raw_value = cosine_weighted_region_mean(
                        raw_field,
                        lat_values,
                        lon_values,
                        region_box,
                    )
                    detrended_value = cosine_weighted_region_mean(
                        detrended_field,
                        lat_values,
                        lon_values,
                        region_box,
                    )

                    if in_period_1:
                        if np.isfinite(raw_value):
                            data_store["p1_raw"][region_name][lag].append(
                                raw_value
                            )
                        if np.isfinite(detrended_value):
                            data_store["p1_det"][region_name][lag].append(
                                detrended_value
                            )

                    if in_period_2:
                        if np.isfinite(raw_value):
                            data_store["p2_raw"][region_name][lag].append(
                                raw_value
                            )
                        if np.isfinite(detrended_value):
                            data_store["p2_det"][region_name][lag].append(
                                detrended_value
                            )

        del data, t2m_values, raw_anomalies, detrended_anomalies
        gc.collect()

    def aggregate_store(store):
        output = {}

        for region_name in REGION_ORDER:
            means = []
            standard_errors = []

            for lag in LAGS:
                values = store[region_name][lag]

                if len(values) >= 2:
                    means.append(np.mean(values))
                    standard_errors.append(sem(values))
                else:
                    means.append(np.nan)
                    standard_errors.append(np.nan)

            output[region_name] = (
                np.array(means),
                np.array(standard_errors),
            )

        return output

    period1_raw = aggregate_store(data_store["p1_raw"])
    period2_raw = aggregate_store(data_store["p2_raw"])
    period1_detrended = aggregate_store(data_store["p1_det"])
    period2_detrended = aggregate_store(data_store["p2_det"])

    del data_store
    gc.collect()

    return (
        period1_raw,
        period2_raw,
        period1_detrended,
        period2_detrended,
    )


# ---------------------------------------------------------------------
# Cache I/O
# ---------------------------------------------------------------------
def save_lag_cache(
    npz_path,
    period1_raw,
    period2_raw,
    period1_detrended,
    period2_detrended,
):
    """Save lag composite results to an NPZ archive."""
    output = {}

    result_groups = (
        ("r1raw", period1_raw),
        ("r2raw", period2_raw),
        ("r1det", period1_detrended),
        ("r2det", period2_detrended),
    )

    for region_name in REGION_ORDER:
        for tag, result in result_groups:
            output[f"{region_name}__{tag}__mean"] = result[region_name][0]
            output[f"{region_name}__{tag}__sem"] = result[region_name][1]

    np.savez(npz_path, **output)
    print(f"Saved lag-composite cache: {npz_path}")


def load_lag_cache(npz_path):
    """Load lag-composite data from an NPZ archive."""
    if not npz_path.exists():
        raise FileNotFoundError(f"Lag cache not found: {npz_path}")

    data = np.load(npz_path, allow_pickle=False)

    def load_group(tag):
        return {
            region_name: (
                data[f"{region_name}__{tag}__mean"],
                data[f"{region_name}__{tag}__sem"],
            )
            for region_name in REGION_ORDER
        }

    print(f"Loaded lag-composite cache: {npz_path}")

    return (
        load_group("r1raw"),
        load_group("r2raw"),
        load_group("r1det"),
        load_group("r2det"),
    )


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------
def plot_lag_figure(
    period1_raw,
    period2_raw,
    period1_detrended,
    period2_detrended,
    output_file,
):
    """Plot lag composites for raw and detrended anomalies."""
    print(f"Creating lag-composite figure: {output_file}")

    period_colors = ("#1C6AB1", "#ED4043")
    panel_labels = ("(a)", "(b)", "(c)", "(d)", "(e)", "(f)")

    fig, axes = plt.subplots(2, 3, figsize=(20, 10.5))

    row_definitions = (
        (period1_raw, period2_raw, "Raw", 0),
        (period1_detrended, period2_detrended, "Detrended", 1),
    )

    for result1, result2, row_label, row_index in row_definitions:
        for column_index, region_name in enumerate(REGION_ORDER):
            ax = axes[row_index, column_index]

            mean1, sem1 = result1[region_name]
            mean2, sem2 = result2[region_name]

            ax.fill_between(
                LAGS,
                mean1 - 1.96 * sem1,
                mean1 + 1.96 * sem1,
                alpha=0.18,
                color=period_colors[0],
            )
            ax.fill_between(
                LAGS,
                mean2 - 1.96 * sem2,
                mean2 + 1.96 * sem2,
                alpha=0.18,
                color=period_colors[1],
            )

            ax.plot(
                LAGS,
                mean1,
                lw=3.0,
                color=period_colors[0],
                label="1981-1990",
            )
            ax.plot(
                LAGS,
                mean2,
                lw=3.0,
                color=period_colors[1],
                label="2015-2024",
            )

            ax.axvline(0, ls="--", lw=1.0, color="black", alpha=0.7)
            ax.axhline(0, ls="--", lw=1.0, color="black", alpha=0.7)

            ax.set_xlim(LAGS[0], LAGS[-1])
            ax.set_ylim(-2, 3)

            if row_index == 0:
                ax.set_xticks([])
            else:
                ax.set_xticks(np.arange(-20, 61, 10))

            ax.grid(linestyle=":", alpha=0.4)
            ax.tick_params(axis="both", labelsize=14)

            if row_index == 0:
                ax.set_title(
                    REGION_TITLES[region_name],
                    fontsize=18,
                    fontweight="bold",
                    pad=6,
                )

            panel_index = row_index * 3 + column_index

            ax.text(
                0.02,
                0.98,
                panel_labels[panel_index],
                transform=ax.transAxes,
                ha="left",
                va="top",
                fontsize=16,
                fontweight="bold",
                bbox={
                    "facecolor": "white",
                    "edgecolor": "none",
                    "alpha": 0.75,
                    "pad": 1.5,
                },
                zorder=10,
            )

            if row_index == 1:
                ax.set_xlabel(
                    "Lag (days relative to SSW onset)",
                    fontsize=18,
                    fontweight="bold",
                )

            if column_index == 0:
                ax.set_ylabel(
                    f"{row_label}\nT2m anomaly (K)",
                    fontsize=18,
                    fontweight="bold",
                )

            if row_index == 0 and column_index == 0:
                ax.legend(fontsize=16, loc="lower left")

    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved figure: {output_file}")


# ---------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------
def main():
    """Run Figure 2 calculations and plotting."""
    print("=" * 70)
    print(f"SSW source: {SSW_SOURCE}")
    print(f"Output directory: {OUTPUT_DIR}")
    print("=" * 70)

    ssw_df = read_ssw_events()

    if NPZ_LAG.exists():
        print("\nLoading existing lag-composite cache")

        (
            period1_raw,
            period2_raw,
            period1_detrended,
            period2_detrended,
        ) = load_lag_cache(NPZ_LAG)

    else:
        baseline_climatology, lat_values, lon_values = (
            build_baseline_climatology()
        )

        trend_params = build_trend_params(baseline_climatology)

        (
            period1_raw,
            period2_raw,
            period1_detrended,
            period2_detrended,
        ) = build_lag_composites(
            ssw_df,
            baseline_climatology,
            trend_params,
            lat_values,
            lon_values,
        )

        save_lag_cache(
            NPZ_LAG,
            period1_raw,
            period2_raw,
            period1_detrended,
            period2_detrended,
        )

        del baseline_climatology, lat_values, lon_values, trend_params
        gc.collect()

    plot_lag_figure(
        period1_raw,
        period2_raw,
        period1_detrended,
        period2_detrended,
        PNG_OUT_LAG,
    )

    del (
        ssw_df,
        period1_raw,
        period2_raw,
        period1_detrended,
        period2_detrended,
    )
    gc.collect()

    print("\nFinished.")


if __name__ == "__main__":
    main()
