# -*- coding: utf-8 -*-
"""
Reproduce Figure 3: sliding-window SEAS5 post-SSW T2m and zonal-wind
anomaly composites.

The script calculates 10-year sliding-window composites for three SSW
phases:

    - Precursor phase: day -20 to -1
    - Onset phase: day 0 to +29
    - Decay phase: day +30 to +59

It produces regional 2-m temperature anomaly time series for North
America, Europe, and East Asia, together with 60°N zonal-mean zonal
wind anomalies at 10 and 100 hPa. Both raw and linearly detrended
results are shown.

Input:
    - Daily SEAS5 2-m temperature NetCDF files.
    - Daily SEAS5 zonal-wind NetCDF files at 10 and 100 hPa.
    - A SEAS5 SSW-event CSV generated by 02_seas5_ssw_dates.py.

Output:
    - Cached T2m sliding-window composite data in NPZ format.
    - Cached U sliding-window composite data in NPZ format.
    - Combined Figure 3 PDF written to OUTPUT_DIR.

Raw SEAS5 data are not redistributed with this repository.
Update the paths below before running.

Run:
    python scripts/05_figure3_sliding_t2m_u.py
"""

import gc
from pathlib import Path

import matplotlib.gridspec as gridspec
import matplotlib.lines as mlines
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
from scipy.stats import theilslopes

plt.rcParams["font.family"] = "Arial"
plt.rcParams["axes.linewidth"] = 1
plt.rcParams["xtick.major.width"] = 1
plt.rcParams["ytick.major.width"] = 1

# ---------------------------------------------------------------------
# User configuration
# ---------------------------------------------------------------------
SEAS5_SSW_CSV_PATH = Path(
    "path/to/analysis_results/"
    "SEAS5_first25members_SSW_dates_NDJFM_events_only_1981_2024.csv"
)

# Replace these placeholder directories with local paths before running.
T2M_DAILY_DIR = Path("path/to/SEAS5/t2m_daily")

U_DAILY_DIRS = {
    10: Path("path/to/SEAS5/u10_daily"),
    100: Path("path/to/SEAS5/u100_daily"),
}

# Generated cache files and Figure 3 will be written here.
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_YEAR = 1981
END_YEAR = 2024
N_MEMBERS = 25

BASELINE_START = 1981
BASELINE_END = 2010

SLIDING_WINDOW = 10

TIME_WINDOWS = (
    (-20, -1, "day -20 to -1"),
    (0, 29, "day 0 to +29"),
    (30, 59, "day +30 to +59"),
)

LEGEND_LABEL_MAP = {
    "day -20 to -1": "Precursor phase",
    "day 0 to +29": "Onset phase",
    "day +30 to +59": "Decay phase",
}

WIN_COLORS = {
    "day -20 to -1": "#7A3E8E",
    "day 0 to +29": "#2166AC",
    "day +30 to +59": "#D73027",
}

T2M_VAR_CANDIDATES = ("2m_temperature",)

REGION_BOXES = {
    "NorthAmerica": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": -140,
        "lon_max": -60,
    },
    "Europe": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 0,
        "lon_max": 40,
    },
    "EastAsia": {
        "lat_min": 45,
        "lat_max": 70,
        "lon_min": 60,
        "lon_max": 120,
    },
}

REGION_TITLES = {
    "NorthAmerica": "North America",
    "Europe": "Europe",
    "EastAsia": "East Asia",
}

REGION_ORDER = ("NorthAmerica", "Europe", "EastAsia")

LEVELS_TO_PLOT = (10, 100)
U_LAT = 60.0

NPZ_TS_T2M = OUTPUT_DIR / (
    f"fig3_SEAS5_SSW_T2m_timeseries_{SLIDING_WINDOW}Y_"
    f"sliding_3regions_cache_daily_3win_m20_{BASELINE_END}.npz"
)

NPZ_TS_U = OUTPUT_DIR / (
    f"fig3_SEAS5_SSW_U_10_100hPa_{SLIDING_WINDOW}Y_"
    f"sliding_cache_daily_3win_m20_{BASELINE_END}.npz"
)

OUTPUT_PDF = OUTPUT_DIR / (
    f"fig3_combined_SEAS5_SSW_T2m_U_"
    f"10yrsliding_{BASELINE_END}.pdf"
)


# ---------------------------------------------------------------------
# General helpers
# ---------------------------------------------------------------------
def month_day_key(timestamp):
    """Return a calendar-day string in MM-DD format."""
    timestamp = pd.Timestamp(timestamp)
    return f"{timestamp.month:02d}-{timestamp.day:02d}"


def get_var_name(ds, candidates):
    """Identify a data variable from preferred candidate names."""
    for variable_name in candidates:
        if variable_name in ds.data_vars:
            return variable_name

    if len(ds.data_vars) == 1:
        return list(ds.data_vars)[0]

    raise ValueError(
        f"Cannot identify variable. "
        f"Available variables: {list(ds.data_vars)}"
    )


def get_lat_lon_dim_names(da):
    """Return latitude and longitude dimension names."""
    lat_candidates = [dim for dim in da.dims if "lat" in dim.lower()]
    lon_candidates = [dim for dim in da.dims if "lon" in dim.lower()]

    if not lat_candidates:
        raise ValueError(f"Latitude dimension not found: {da.dims}")

    if not lon_candidates:
        raise ValueError(f"Longitude dimension not found: {da.dims}")

    return lat_candidates[0], lon_candidates[0]


def get_time_dim_name(da):
    """Return the time dimension name."""
    for name in ("valid_time", "time", "forecast_period"):
        if name in da.dims:
            return name

    raise ValueError(f"Time dimension not found: {da.dims}")


def safe_member_label(number_coord, index):
    """Return an integer ensemble-member label if possible."""
    try:
        return int(number_coord[index])
    except (TypeError, ValueError):
        return index + 1


def make_tag(window_label):
    """Create an NPZ-safe key fragment from a time-window label."""
    return (
        window_label
        .replace(" ", "_")
        .replace("-", "m")
        .replace("+", "p")
    )


# ---------------------------------------------------------------------
# SSW events
# ---------------------------------------------------------------------
def read_ssw_events():
    """Read retained SEAS5 SSW event dates."""
    if not SEAS5_SSW_CSV_PATH.exists():
        raise FileNotFoundError(
            f"SEAS5 SSW-event CSV was not found:\n"
            f"  {SEAS5_SSW_CSV_PATH}\n\n"
            "Run 02_seas5_ssw_dates.py first or update "
            "SEAS5_SSW_CSV_PATH."
        )

    df = pd.read_csv(SEAS5_SSW_CSV_PATH)

    required_columns = ("init_year", "member", "ssw_date")

    for column in required_columns:
        if column not in df.columns:
            raise ValueError(
                f"SEAS5 SSW-event CSV is missing required column: {column}"
            )

    df["ssw_date"] = pd.to_datetime(
        df["ssw_date"],
        errors="coerce",
    ).dt.normalize()

    df = df.dropna(subset=["ssw_date"]).copy()

    df = df[
        (df["init_year"] >= START_YEAR)
        & (df["init_year"] <= END_YEAR)
    ].copy()

    df["member"] = df["member"].astype(int)
    df["month"] = df["ssw_date"].dt.month

    df = df[
        df["month"].isin((11, 12, 1, 2, 3))
    ].copy()

    df = df.sort_values(
        ["init_year", "member", "ssw_date"]
    ).reset_index(drop=True)

    if df.empty:
        raise RuntimeError("No valid SEAS5 SSW events were loaded.")

    print(f"Loaded {len(df)} SEAS5 SSW events")

    return df


# ---------------------------------------------------------------------
# Trend and plot helpers
# ---------------------------------------------------------------------
def block_bootstrap_trend(
    x_values,
    mean_values,
    n_boot=1000,
    block_size=3,
    seed=42,
):
    """
    Estimate a Theil-Sen trend and block-bootstrap p value.

    The bootstrap samples contiguous index blocks, preserving part of
    the serial dependence in overlapping sliding-window time series.
    """
    random_generator = np.random.default_rng(seed)
    n_values = len(mean_values)

    if n_values < 3:
        return np.nan, np.nan

    observed_slope = theilslopes(mean_values, x_values).slope
    bootstrap_slopes = []

    for _ in range(n_boot):
        indices = []

        while len(indices) < n_values:
            start = random_generator.integers(
                0,
                max(1, n_values - block_size + 1),
            )

            indices.extend(
                range(start, min(start + block_size, n_values))
            )

        sampled_indices = np.array(indices[:n_values])

        bootstrap_slopes.append(
            theilslopes(
                mean_values[sampled_indices],
                x_values,
            ).slope
        )

    bootstrap_slopes = np.array(bootstrap_slopes)
    centered_slopes = bootstrap_slopes - np.mean(bootstrap_slopes)

    p_value = float(
        np.mean(np.abs(centered_slopes) >= np.abs(observed_slope))
    )

    return observed_slope, p_value


def p_to_sig(p_value):
    """Return significance symbols for a p value."""
    if not np.isfinite(p_value):
        return ""

    if p_value < 0.01:
        return "**"

    if p_value < 0.05:
        return "*"

    return ""


def get_line_trend_label(x_values, y_values, fmt="{:+.2f}"):
    """Return end-point coordinates and a per-decade trend label."""
    valid = np.isfinite(y_values)

    if valid.sum() <= 5:
        return None, None, None

    x_valid = x_values[valid]
    y_valid = y_values[valid]

    trend_result = theilslopes(y_valid, x_valid)

    _, p_value = block_bootstrap_trend(
        x_valid,
        y_valid,
        n_boot=1000,
        block_size=3,
    )

    slope_per_decade = trend_result.slope * 10.0

    label = fmt.format(slope_per_decade) + p_to_sig(p_value)

    return x_valid[-1], y_valid[-1], label


def adjust_label_positions(label_items, ymin, ymax, min_gap):
    """Adjust right-side text labels vertically to reduce overlap."""
    if not label_items:
        return label_items

    sorted_items = sorted(label_items, key=lambda item: item["y"])

    sorted_items[0]["y_adj"] = sorted_items[0]["y"]

    for index in range(1, len(sorted_items)):
        sorted_items[index]["y_adj"] = max(
            sorted_items[index]["y"],
            sorted_items[index - 1]["y_adj"] + min_gap,
        )

    for _ in range(2):
        top_overflow = sorted_items[-1]["y_adj"] - ymax

        if top_overflow > 0:
            for item in sorted_items:
                item["y_adj"] -= top_overflow

        bottom_overflow = ymin - sorted_items[0]["y_adj"]

        if bottom_overflow > 0:
            for item in sorted_items:
                item["y_adj"] += bottom_overflow

        for index in range(len(sorted_items) - 2, -1, -1):
            maximum_position = (
                sorted_items[index + 1]["y_adj"] - min_gap
            )

            if sorted_items[index]["y_adj"] > maximum_position:
                sorted_items[index]["y_adj"] = maximum_position

    return sorted_items


def add_right_side_labels(ax, label_items, xpad, fontsize=11):
    """Add non-overlapping raw and detrended trend labels."""
    if not label_items:
        return

    ymin, ymax = ax.get_ylim()
    y_range = ymax - ymin

    adjusted_items = adjust_label_positions(
        label_items,
        ymin - 0.20 * y_range,
        ymax + 0.20 * y_range,
        min_gap=0.06 * y_range,
    )

    for item in adjusted_items:
        ax.text(
            item["x"] + xpad,
            item["y_adj"],
            item["label"],
            color=item["color"],
            fontsize=fontsize,
            ha="left",
            va="center",
            fontweight="bold",
            clip_on=False,
        )


def style_axis(ax):
    """Apply shared formatting to time-series axes."""
    for side in ("left", "bottom", "top", "right"):
        ax.spines[side].set_visible(True)
        ax.spines[side].set_linewidth(0.8)

    ax.grid(
        True,
        axis="both",
        linestyle=":",
        alpha=0.4,
        lw=0.7,
    )


# ---------------------------------------------------------------------
# Daily data loading
# ---------------------------------------------------------------------
def load_one_year_daily(
    year,
    daily_dir,
    file_pattern,
    var_candidates,
    flip_lat=True,
    wrap_lon=True,
):
    """Load and standardize one daily SEAS5 file."""
    input_file = daily_dir / file_pattern.format(year=year)

    if not input_file.exists():
        print(f"  Missing input file: {input_file.name}")
        return None

    try:
        ds = xr.open_dataset(input_file)

        try:
            variable_name = get_var_name(ds, var_candidates)
            da = ds[variable_name].load()
        finally:
            ds.close()

        if "number" not in da.dims:
            raise ValueError(
                f"Ensemble-member dimension 'number' not found: {da.dims}"
            )

        da = da.transpose(
            "number",
            *[dimension for dimension in da.dims if dimension != "number"],
        )
        da = da.isel(number=slice(0, N_MEMBERS))

        for dimension in list(da.dims):
            is_non_spatial_singleton = (
                dimension != "number"
                and da.sizes[dimension] == 1
                and "lat" not in dimension.lower()
                and "lon" not in dimension.lower()
                and "time" not in dimension.lower()
                and "valid" not in dimension.lower()
            )

            if is_non_spatial_singleton:
                da = da.squeeze(dimension, drop=True)

        lat_name, lon_name = get_lat_lon_dim_names(da)
        time_name = get_time_dim_name(da)

        if flip_lat and da[lat_name].values[0] < da[lat_name].values[-1]:
            da = da.isel({lat_name: slice(None, None, -1)})

        if wrap_lon:
            original_lon = da[lon_name].values

            if np.nanmax(original_lon) > 180:
                converted_lon = np.where(
                    original_lon > 180,
                    original_lon - 360,
                    original_lon,
                )
                sort_index = np.argsort(converted_lon)

                da = da.isel({lon_name: sort_index})
                da = da.assign_coords(
                    {lon_name: converted_lon[sort_index]}
                )

        times = pd.to_datetime(da[time_name].values).normalize()

        member_labels = [
            safe_member_label(da["number"].values, index)
            for index in range(da.sizes["number"])
        ]

        values = da.values.astype(np.float32)
        lat_values = da[lat_name].values.copy()
        lon_values = da[lon_name].values.copy()

        return {
            "arr": values,
            "times": times,
            "monthday": np.array(
                [month_day_key(timestamp) for timestamp in times]
            ),
            "member_labels": member_labels,
            "member_to_idx": {
                member: index
                for index, member in enumerate(member_labels)
            },
            "time_to_idx": {
                pd.Timestamp(timestamp): index
                for index, timestamp in enumerate(times)
            },
            "lat_vals": lat_values,
            "lon_vals": lon_values,
        }

    except Exception as error:
        print(f"  Failed to load year {year}: {error}")
        gc.collect()
        return None


# ---------------------------------------------------------------------
# Extraction functions
# ---------------------------------------------------------------------
def cosine_weighted_mean(field_2d, lat_values, lon_values, region_box):
    """Calculate cosine-latitude-weighted regional mean T2m anomaly."""
    lat_mask = (
        (lat_values >= region_box["lat_min"])
        & (lat_values <= region_box["lat_max"])
    )
    lon_mask = (
        (lon_values >= region_box["lon_min"])
        & (lon_values <= region_box["lon_max"])
    )

    if not np.any(lat_mask) or not np.any(lon_mask):
        return np.nan

    subset = field_2d[np.ix_(lat_mask, lon_mask)]

    latitude_weights = np.cos(np.deg2rad(lat_values[lat_mask]))
    weights_2d = latitude_weights[:, None] * np.ones(lon_mask.sum())

    valid = np.isfinite(subset)

    if not np.any(valid):
        return np.nan

    return float(
        np.nansum(subset * weights_2d * valid)
        / np.nansum(weights_2d * valid)
    )


def zonal_mean_at_lat(field_2d, lat_values, lon_values, target_lat):
    """Calculate the zonal mean at the nearest latitude to target_lat."""
    del lon_values

    latitude_index = np.argmin(np.abs(lat_values - target_lat))
    row = field_2d[latitude_index, :]
    valid = np.isfinite(row)

    if not np.any(valid):
        return np.nan

    return float(np.nanmean(row[valid]))


# ---------------------------------------------------------------------
# Daily climatology and trend parameters
# ---------------------------------------------------------------------
def build_baseline_climatology(
    years,
    daily_dir,
    file_pattern,
    var_candidates,
):
    """Build an ensemble-mean, 11-day-smoothed daily climatology."""
    print(
        f"  Building baseline climatology "
        f"{years[0]}-{years[-1]} with +/-5-day smoothing"
    )

    day_of_year_fields = {}
    lat_values = None
    lon_values = None

    for year in years:
        data = load_one_year_daily(
            year,
            daily_dir,
            file_pattern,
            var_candidates,
        )

        if data is None:
            continue

        if lat_values is None:
            lat_values = data["lat_vals"]
            lon_values = data["lon_vals"]

        ensemble_mean = data["arr"].mean(axis=0)
        day_of_years = pd.to_datetime(data["times"]).dayofyear.values

        for index, day_of_year in enumerate(day_of_years):
            day_of_year_fields.setdefault(day_of_year, []).append(
                ensemble_mean[index].astype(np.float32)
            )

        del data, ensemble_mean, day_of_years
        gc.collect()

    if not day_of_year_fields or lat_values is None or lon_values is None:
        raise RuntimeError(
            "No baseline daily files were loaded. Check input paths."
        )

    n_lat = len(lat_values)
    n_lon = len(lon_values)

    climatology_raw = np.full(
        (366, n_lat, n_lon),
        np.nan,
        dtype=np.float32,
    )

    for day_of_year, fields in day_of_year_fields.items():
        climatology_raw[day_of_year - 1] = np.nanmean(
            np.stack(fields, axis=0),
            axis=0,
        )

    del day_of_year_fields
    gc.collect()

    window = 11
    padding = window // 2

    climatology_padded = np.concatenate(
        [
            climatology_raw[-padding:],
            climatology_raw,
            climatology_raw[:padding],
        ],
        axis=0,
    )

    climatology_smoothed = np.full_like(climatology_raw, np.nan)

    for index in range(366):
        window_values = climatology_padded[index:index + window]

        if np.isfinite(window_values).any():
            climatology_smoothed[index] = np.nanmean(
                window_values,
                axis=0,
            )

    del climatology_padded, climatology_raw
    gc.collect()

    climatology = {}

    for timestamp in pd.date_range("2001-01-01", "2001-12-31"):
        climatology[month_day_key(timestamp)] = (
            climatology_smoothed[timestamp.dayofyear - 1]
        )

    del climatology_smoothed
    gc.collect()

    print(f"  Baseline climatology completed: {len(climatology)} days")

    return climatology, lat_values, lon_values


def build_trend_params(
    climatology,
    daily_dir,
    file_pattern,
    var_candidates,
):
    """
    Calculate cross-year linear trend coefficients for each calendar day.

    Parameters are calculated from ensemble-mean daily anomalies.
    """
    print("  Building daily trend parameters")

    calendar_day_anomalies = {}

    for year in range(START_YEAR, END_YEAR + 1):
        data = load_one_year_daily(
            year,
            daily_dir,
            file_pattern,
            var_candidates,
        )

        if data is None:
            continue

        ensemble_mean = data["arr"].mean(axis=0)

        for index, timestamp in enumerate(data["times"]):
            calendar_day = (timestamp.month, timestamp.day)

            climatology_field = climatology.get(
                month_day_key(timestamp)
            )

            if climatology_field is None:
                continue

            anomaly = (
                ensemble_mean[index] - climatology_field
            ).astype(np.float32)

            calendar_day_anomalies.setdefault(
                calendar_day,
                [],
            ).append((year, anomaly))

        del data, ensemble_mean
        gc.collect()

    trend_params = {}

    for calendar_day, entries in calendar_day_anomalies.items():
        if len(entries) < 2:
            continue

        year_values = np.array(
            [entry[0] for entry in entries],
            dtype=np.float64,
        )

        mean_year = float(year_values.mean())
        centered_years = year_values - mean_year
        denominator = np.sum(centered_years ** 2)

        if denominator < 1e-10:
            continue

        anomaly_stack = np.stack(
            [entry[1] for entry in entries],
            axis=0,
        ).astype(np.float64)

        slope = (
            centered_years[:, None, None] * anomaly_stack
        ).sum(axis=0) / denominator

        # Mean anomaly at mean_year; retained for cache consistency.
        intercept = anomaly_stack.mean(axis=0)

        trend_params[calendar_day] = (
            intercept.astype(np.float32),
            slope.astype(np.float32),
            mean_year,
        )

        del (
            year_values,
            centered_years,
            anomaly_stack,
            slope,
            intercept,
        )

    del calendar_day_anomalies
    gc.collect()

    print(f"  Trend parameters completed: {len(trend_params)} days")

    return trend_params


# ---------------------------------------------------------------------
# Event extraction and sliding composites
# ---------------------------------------------------------------------
def extract_event_samples(
    ssw_df,
    climatology,
    trend_params,
    lat_values,
    lon_values,
    daily_dir,
    file_pattern,
    var_candidates,
    extract_function,
):
    """
    Extract raw and detrended event-mean values for each SSW event and
    each defined time window.
    """
    event_cache = {
        window_label: {}
        for _, _, window_label in TIME_WINDOWS
    }

    for year in range(START_YEAR, END_YEAR + 1):
        events_this_year = ssw_df[
            ssw_df["init_year"] == year
        ]

        if events_this_year.empty:
            continue

        data = load_one_year_daily(
            year,
            daily_dir,
            file_pattern,
            var_candidates,
        )

        if data is None:
            continue

        values = data["arr"]
        monthday = data["monthday"]
        times = data["times"]
        member_to_index = data["member_to_idx"]
        time_to_index = data["time_to_idx"]

        n_time = values.shape[1]
        n_lat = values.shape[2]
        n_lon = values.shape[3]

        climatology_array = np.full(
            (n_time, n_lat, n_lon),
            np.nan,
            dtype=np.float32,
        )

        for index, key in enumerate(monthday):
            climatology_field = climatology.get(key)

            if climatology_field is not None:
                climatology_array[index] = climatology_field

        raw_anomalies = values - climatology_array[None, :, :, :]
        detrended_anomalies = raw_anomalies.copy()

        for index, timestamp in enumerate(times):
            calendar_day = (timestamp.month, timestamp.day)
            coefficients = trend_params.get(calendar_day)

            if coefficients is None:
                continue

            _, slope, mean_year = coefficients

            # Remove only the time-varying trend component so the
            # anomaly baseline itself remains unchanged.
            detrended_anomalies[:, index] -= (
                slope * (year - mean_year)
            )[None, :, :]

        del climatology_array
        gc.collect()

        for _, row in events_this_year.iterrows():
            member = int(row["member"])
            onset_date = pd.Timestamp(row["ssw_date"]).normalize()

            if member not in member_to_index:
                continue

            if onset_date not in time_to_index:
                continue

            member_index = member_to_index[member]
            onset_index = time_to_index[onset_date]

            for day_start, day_end, window_label in TIME_WINDOWS:
                start_index = onset_index + day_start
                end_index = onset_index + day_end + 1

                if start_index < 0 or end_index > n_time:
                    continue

                raw_field = np.nanmean(
                    raw_anomalies[
                        member_index,
                        start_index:end_index,
                    ],
                    axis=0,
                )

                detrended_field = np.nanmean(
                    detrended_anomalies[
                        member_index,
                        start_index:end_index,
                    ],
                    axis=0,
                )

                event_key = (
                    year,
                    member,
                    onset_date,
                )

                event_cache[window_label][event_key] = (
                    extract_function(
                        raw_field,
                        lat_values,
                        lon_values,
                    ),
                    extract_function(
                        detrended_field,
                        lat_values,
                        lon_values,
                    ),
                )

                del raw_field, detrended_field

        del values, raw_anomalies, detrended_anomalies, data
        gc.collect()

    return event_cache


def aggregate_sliding_windows(ssw_df, event_cache):
    """Aggregate event values into overlapping SLIDING_WINDOW-year means."""
    first_year = int(ssw_df["init_year"].min())
    last_year = int(ssw_df["init_year"].max())

    windows = [
        (year, year + SLIDING_WINDOW - 1)
        for year in range(
            first_year,
            last_year - SLIDING_WINDOW + 2,
        )
    ]

    time_series = {}

    for _, _, window_label in TIME_WINDOWS:
        cache = event_cache[window_label]

        x_centers = []
        window_labels = []
        raw_means = []
        raw_standard_errors = []
        detrended_means = []
        detrended_standard_errors = []
        sample_counts = []

        for start_year, end_year in windows:
            events_in_window = ssw_df[
                (ssw_df["init_year"] >= start_year)
                & (ssw_df["init_year"] <= end_year)
            ]

            raw_values = []
            detrended_values = []

            for _, row in events_in_window.iterrows():
                event_key = (
                    int(row["init_year"]),
                    int(row["member"]),
                    pd.Timestamp(row["ssw_date"]).normalize(),
                )

                if event_key not in cache:
                    continue

                raw_value, detrended_value = cache[event_key]
                raw_values.append(raw_value)
                detrended_values.append(detrended_value)

            sample_count = len(raw_values)

            raw_means.append(
                np.nanmean(raw_values)
                if sample_count > 0 else np.nan
            )
            detrended_means.append(
                np.nanmean(detrended_values)
                if sample_count > 0 else np.nan
            )

            raw_standard_errors.append(
                np.nanstd(raw_values, ddof=1) / np.sqrt(sample_count)
                if sample_count > 1 else np.nan
            )
            detrended_standard_errors.append(
                np.nanstd(detrended_values, ddof=1) / np.sqrt(sample_count)
                if sample_count > 1 else np.nan
            )

            sample_counts.append(sample_count)
            x_centers.append(
                start_year + (SLIDING_WINDOW - 1) / 2.0
            )
            window_labels.append(f"{start_year}-{end_year}")

        time_series[window_label] = {
            "xc": np.array(x_centers),
            "wl": window_labels,
            "rm": np.array(raw_means),
            "rs": np.array(raw_standard_errors),
            "dm": np.array(detrended_means),
            "ds": np.array(detrended_standard_errors),
            "rn": np.array(sample_counts),
        }

    return time_series


# ---------------------------------------------------------------------
# T2m pipeline
# ---------------------------------------------------------------------
def compute_t2m_sliding(ssw_df):
    """Compute regional sliding-window T2m anomaly composites."""
    print("\n" + "=" * 70)
    print("T2m sliding-window pipeline")

    baseline_years = list(range(BASELINE_START, BASELINE_END + 1))
    file_pattern = "SEAS5_2mt_NH_{year}11_system51_m25_daily.nc"

    climatology, lat_values, lon_values = build_baseline_climatology(
        baseline_years,
        T2M_DAILY_DIR,
        file_pattern,
        T2M_VAR_CANDIDATES,
    )

    trend_params = build_trend_params(
        climatology,
        T2M_DAILY_DIR,
        file_pattern,
        T2M_VAR_CANDIDATES,
    )

    all_time_series = {}

    for region_name, region_box in REGION_BOXES.items():
        print(f"  Extracting region: {region_name}")

        def extract_function(
            field,
            field_lat_values,
            field_lon_values,
            selected_region=region_box,
        ):
            return cosine_weighted_mean(
                field,
                field_lat_values,
                field_lon_values,
                selected_region,
            )

        event_cache = extract_event_samples(
            ssw_df,
            climatology,
            trend_params,
            lat_values,
            lon_values,
            T2M_DAILY_DIR,
            file_pattern,
            T2M_VAR_CANDIDATES,
            extract_function,
        )

        all_time_series[region_name] = aggregate_sliding_windows(
            ssw_df,
            event_cache,
        )

        del event_cache
        gc.collect()

    del climatology, trend_params, lat_values, lon_values
    gc.collect()

    save_t2m_sliding_cache(all_time_series)

    return all_time_series


def save_t2m_sliding_cache(all_time_series):
    """Save regional T2m sliding-window composites as NPZ."""
    output = {}

    for region_name, time_series in all_time_series.items():
        for window_label, values in time_series.items():
            prefix = f"{region_name}__{make_tag(window_label)}"

            for key in ("xc", "wl", "rm", "rs", "dm", "ds", "rn"):
                value = values[key]

                if key == "wl":
                    value = np.array(value, dtype=str)

                output[f"{prefix}__{key}"] = value

    np.savez(NPZ_TS_T2M, **output)

    print(f"Saved T2m cache: {NPZ_TS_T2M}")


def load_t2m_sliding():
    """Load regional T2m sliding-window composites from NPZ."""
    data = np.load(NPZ_TS_T2M, allow_pickle=False)
    all_time_series = {}

    for region_name in REGION_ORDER:
        time_series = {}

        for _, _, window_label in TIME_WINDOWS:
            prefix = f"{region_name}__{make_tag(window_label)}"

            time_series[window_label] = {
                "xc": data[f"{prefix}__xc"],
                "wl": list(data[f"{prefix}__wl"].astype(str)),
                "rm": data[f"{prefix}__rm"],
                "rs": data[f"{prefix}__rs"],
                "dm": data[f"{prefix}__dm"],
                "ds": data[f"{prefix}__ds"],
                "rn": data[f"{prefix}__rn"].astype(int),
            }

        all_time_series[region_name] = time_series

    print(f"Loaded T2m cache: {NPZ_TS_T2M}")

    return all_time_series


# ---------------------------------------------------------------------
# Zonal-wind pipeline
# ---------------------------------------------------------------------
def compute_u_sliding(ssw_df):
    """Compute sliding-window zonal-wind anomaly composites."""
    print("\n" + "=" * 70)
    print("Zonal-wind sliding-window pipeline")

    all_time_series = {}
    baseline_years = list(range(BASELINE_START, BASELINE_END + 1))

    for level in LEVELS_TO_PLOT:
        print(f"\n  Processing {level} hPa")

        daily_dir = U_DAILY_DIRS[level]
        file_pattern = (
            f"SEAS5_u{level}hPa_NH_{{year}}11_system51_m25_daily.nc"
        )

        variable_candidates = (
            "u",
            f"u{level}",
            "uwnd",
            "var131",
        )

        climatology, lat_values, lon_values = build_baseline_climatology(
            baseline_years,
            daily_dir,
            file_pattern,
            variable_candidates,
        )

        trend_params = build_trend_params(
            climatology,
            daily_dir,
            file_pattern,
            variable_candidates,
        )

        def extract_function(
            field,
            field_lat_values,
            field_lon_values,
            target_latitude=U_LAT,
        ):
            return zonal_mean_at_lat(
                field,
                field_lat_values,
                field_lon_values,
                target_latitude,
            )

        event_cache = extract_event_samples(
            ssw_df,
            climatology,
            trend_params,
            lat_values,
            lon_values,
            daily_dir,
            file_pattern,
            variable_candidates,
            extract_function,
        )

        all_time_series[level] = aggregate_sliding_windows(
            ssw_df,
            event_cache,
        )

        del (
            climatology,
            trend_params,
            event_cache,
            lat_values,
            lon_values,
        )
        gc.collect()

    save_u_sliding_cache(all_time_series)

    return all_time_series


def save_u_sliding_cache(all_time_series):
    """Save zonal-wind sliding-window composites as NPZ."""
    output = {}

    for level, time_series in all_time_series.items():
        for window_label, values in time_series.items():
            prefix = f"u{level}__{make_tag(window_label)}"

            for key in ("xc", "wl", "rm", "rs", "dm", "ds", "rn"):
                value = values[key]

                if key == "wl":
                    value = np.array(value, dtype=str)

                output[f"{prefix}__{key}"] = value

    np.savez(NPZ_TS_U, **output)

    print(f"Saved zonal-wind cache: {NPZ_TS_U}")


def load_u_sliding():
    """Load zonal-wind sliding-window composites from NPZ."""
    data = np.load(NPZ_TS_U, allow_pickle=False)
    all_time_series = {}

    for level in LEVELS_TO_PLOT:
        time_series = {}

        for _, _, window_label in TIME_WINDOWS:
            prefix = f"u{level}__{make_tag(window_label)}"

            time_series[window_label] = {
                "xc": data[f"{prefix}__xc"],
                "wl": list(data[f"{prefix}__wl"].astype(str)),
                "rm": data[f"{prefix}__rm"],
                "rs": data[f"{prefix}__rs"],
                "dm": data[f"{prefix}__dm"],
                "ds": data[f"{prefix}__ds"],
                "rn": data[f"{prefix}__rn"].astype(int),
            }

        all_time_series[level] = time_series

    print(f"Loaded zonal-wind cache: {NPZ_TS_U}")

    return all_time_series


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------
def plot_one_panel(
    ax,
    time_series,
    y_limits,
    xpad_fraction=0.02,
    trend_fontsize=11,
):
    """Plot raw and detrended sliding-window time series in one panel."""
    raw_label_items = []
    detrended_label_items = []

    for _, _, window_label in TIME_WINDOWS:
        values = time_series[window_label]

        x_centers = values["xc"]
        raw_means = values["rm"]
        raw_errors = values["rs"]
        detrended_means = values["dm"]
        detrended_errors = values["ds"]

        color = WIN_COLORS[window_label]

        ax.plot(
            x_centers,
            raw_means,
            color=color,
            lw=2.5,
            ls="-",
            zorder=4,
        )
        ax.fill_between(
            x_centers,
            raw_means - raw_errors,
            raw_means + raw_errors,
            color=color,
            alpha=0.12,
            zorder=2,
        )

        ax.plot(
            x_centers,
            detrended_means,
            color=color,
            lw=2.5,
            ls="--",
            zorder=4,
        )
        ax.fill_between(
            x_centers,
            detrended_means - detrended_errors,
            detrended_means + detrended_errors,
            color=color,
            alpha=0.07,
            zorder=2,
        )

        x_end, y_end, label = get_line_trend_label(
            x_centers,
            raw_means,
        )

        if label:
            raw_label_items.append(
                {
                    "x": x_end,
                    "y": y_end,
                    "label": f"{label} (R)",
                    "color": color,
                }
            )

        x_end, y_end, label = get_line_trend_label(
            x_centers,
            detrended_means,
        )

        if label:
            detrended_label_items.append(
                {
                    "x": x_end,
                    "y": y_end,
                    "label": f"{label} (D)",
                    "color": color,
                }
            )

    ax.axhline(0, color="black", lw=0.9, zorder=3)

    reference_window = TIME_WINDOWS[0][2]
    x_reference = time_series[reference_window]["xc"]
    window_labels = time_series[reference_window]["wl"]

    tick_step = 5
    tick_indices = np.arange(0, len(x_reference), tick_step)

    tick_labels = [
        window_labels[index].replace("-", "–")
        for index in tick_indices
    ]

    ax.set_xticks(x_reference[tick_indices])
    ax.set_xticklabels(
        tick_labels,
        rotation=35,
        ha="right",
        fontsize=12,
    )

    x_range = x_reference[-1] - x_reference[0]

    clipped_raw_labels = [
        {
            **item,
            "y": np.clip(item["y"], y_limits[0], y_limits[1]),
        }
        for item in raw_label_items
    ]

    clipped_detrended_labels = [
        {
            **item,
            "y": np.clip(item["y"], y_limits[0], y_limits[1]),
        }
        for item in detrended_label_items
    ]

    ax.set_xlim(x_reference[0] - 0.3, x_reference[-1] + 0.3)
    ax.set_ylim(y_limits)
    ax.autoscale(enable=False)
    ax.tick_params(axis="y", labelsize=11)

    add_right_side_labels(
        ax,
        clipped_raw_labels + clipped_detrended_labels,
        x_range * xpad_fraction,
        fontsize=trend_fontsize,
    )

    ax.set_xlim(x_reference[0] - 0.3, x_reference[-1] + 0.3)
    ax.set_ylim(y_limits)

    style_axis(ax)


def plot_combined_figure(all_t2m, all_u, output_file):
    """Create the five-panel Figure 3 PDF."""
    print(f"\nCreating Figure 3: {output_file}")

    fig = plt.figure(figsize=(21, 10))

    grid_top = gridspec.GridSpec(
        1,
        3,
        figure=fig,
        left=0.06,
        right=0.88,
        top=0.93,
        bottom=0.55,
        wspace=0.32,
    )

    grid_bottom = gridspec.GridSpec(
        1,
        2,
        figure=fig,
        left=0.20,
        right=0.75,
        top=0.43,
        bottom=0.08,
        wspace=0.35,
    )

    panel_labels = ("(a)", "(b)", "(c)", "(d)", "(e)")
    top_axes = []

    for column_index, region_name in enumerate(REGION_ORDER):
        ax = fig.add_subplot(grid_top[0, column_index])
        top_axes.append(ax)

        plot_one_panel(
            ax,
            all_t2m[region_name],
            y_limits=(-1.5, 2.0),
        )

        ax.set_title(
            REGION_TITLES[region_name],
            fontsize=16,
            fontweight="bold",
            pad=5,
        )

        ax.text(
            0.02,
            0.97,
            panel_labels[column_index],
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=16,
            fontweight="bold",
            bbox={
                "facecolor": "white",
                "edgecolor": "none",
                "alpha": 0.7,
            },
        )

        if column_index == 0:
            ax.set_ylabel(
                "T2m anomaly (K)",
                fontsize=16,
                fontweight="bold",
            )

    u_titles = {
        10: "10 hPa U (60°N)",
        100: "100 hPa U (60°N)",
    }

    u_y_limits = {
        10: (-20, 8),
        100: (-6, 4),
    }

    for column_index, level in enumerate(LEVELS_TO_PLOT):
        ax = fig.add_subplot(grid_bottom[0, column_index])

        plot_one_panel(
            ax,
            all_u[level],
            y_limits=u_y_limits[level],
        )

        ax.set_title(
            u_titles[level],
            fontsize=16,
            fontweight="bold",
            pad=5,
        )

        ax.text(
            0.02,
            0.97,
            panel_labels[3 + column_index],
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=16,
            fontweight="bold",
            bbox={
                "facecolor": "white",
                "edgecolor": "none",
                "alpha": 0.7,
            },
        )

        if column_index == 0:
            ax.set_ylabel(
                "U anomaly (m s$^{-1}$)",
                fontsize=16,
                fontweight="bold",
            )

    solid_line = mlines.Line2D(
        [],
        [],
        color="grey",
        ls="-",
        lw=2,
        label="Solid = Raw (R)",
    )

    dashed_line = mlines.Line2D(
        [],
        [],
        color="grey",
        ls="--",
        lw=2,
        label="Dashed = Detrended (D)",
    )

    shading_line = mlines.Line2D(
        [],
        [],
        color="grey",
        ls="-",
        lw=6,
        alpha=0.3,
        label="+/-1 SE",
    )

    phase_handles = [
        mlines.Line2D(
            [],
            [],
            color=WIN_COLORS[window_label],
            ls="-",
            lw=2.5,
            label=LEGEND_LABEL_MAP[window_label],
        )
        for _, _, window_label in TIME_WINDOWS
    ]

    top_axes[0].legend(
        handles=[
            solid_line,
            dashed_line,
            shading_line,
            *phase_handles,
        ],
        loc="lower left",
        fontsize=12,
        framealpha=0.88,
        ncol=2,
        handlelength=2.0,
    )

    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved Figure 3: {output_file}")


# ---------------------------------------------------------------------
# Main workflow
# ---------------------------------------------------------------------
def main():
    """Run the Figure 3 workflow."""
    print("=" * 70)
    print(f"Output figure: {OUTPUT_PDF}")
    print("=" * 70)

    ssw_df = read_ssw_events()

    if NPZ_TS_T2M.exists():
        all_t2m = load_t2m_sliding()
    else:
        all_t2m = compute_t2m_sliding(ssw_df)

    gc.collect()

    if NPZ_TS_U.exists():
        all_u = load_u_sliding()
    else:
        all_u = compute_u_sliding(ssw_df)

    gc.collect()

    plot_combined_figure(
        all_t2m,
        all_u,
        OUTPUT_PDF,
    )

    del ssw_df, all_t2m, all_u
    gc.collect()

    print("\nFinished.")


if __name__ == "__main__":
    main()
